import { ReportData } from './ReportHistory.types';

export const reportRows: ReportData[] = [
  {
    plantId: 'plant-001',
    orgName: 'org-001',
    reportName: 'Monthly Energy Report',
    version: 'v1.2',
    plantName: 'Solar Plant A',
    organisationName: 'GreenTech Ltd.',
  },
  {
    plantId: 'plant-002',
    orgName: 'org-002',
    reportName: 'Water Usage Report',
    version: 'v3.1',
    plantName: 'Hydro Plant B',
    organisationName: 'EcoWater Corp.',
  },
  {
    plantId: 'plant-003',
    orgName: 'org-003',
    reportName: 'Water Usage Report',
    version: 'v3.1',
    plantName: 'Hydro Plant B',
    organisationName: 'EcoWater Corp.',
  },
  {
    plantId: 'plant-004',
    orgName: 'org-004',
    reportName: 'Water Usage Report',
    version: 'v3.1',
    plantName: 'Hydro Plant B',
    organisationName: 'EcoWater Corp.',
  },
  {
    plantId: 'plant-005',
    orgName: 'org-005',
    reportName: 'Water Usage Report',
    version: 'v3.1',
    plantName: 'Hydro Plant B',
    organisationName: 'EcoWater Corp.',
  },
  {
    plantId: 'plant-006',
    orgName: 'org-006',
    reportName: 'Water Usage Report',
    version: 'v3.1',
    plantName: 'Hydro Plant B',
    organisationName: 'EcoWater Corp.',
  },
  {
    plantId: 'plant-007',
    orgName: 'org-007',
    reportName: 'Water Usage Report',
    version: 'v3.1',
    plantName: 'Hydro Plant B',
    organisationName: 'EcoWater Corp.',
  },
  {
    plantId: 'plant-008',
    orgName: 'org-008',
    reportName: 'Water Usage Report',
    version: 'v3.1',
    plantName: 'Hydro Plant B',
    organisationName: 'EcoWater Corp.',
  },
  {
    plantId: 'plant-009',
    orgName: 'org-009',
    reportName: 'Water Usage Report',
    version: 'v3.1',
    plantName: 'Hydro Plant B',
    organisationName: 'EcoWater Corp.',
  },
  {
    plantId: 'plant-010',
    orgName: 'org-010',
    reportName: 'Water Usage Report',
    version: 'v3.1',
    plantName: 'Hydro Plant B',
    organisationName: 'EcoWater Corp.',
  },
  {
    plantId: 'plant-011',
    orgName: 'org-011',
    reportName: 'Emissions Summary',
    version: 'v2.0',
    plantName: 'Thermal Plant C',
    organisationName: 'CarbonX Inc.',
  },
  {
    plantId: 'plant-012',
    orgName: 'org-012',
    reportName: 'Emissions Summary',
    version: 'v2.0',
    plantName: 'Thermal Plant C',
    organisationName: 'CarbonX Inc.',
  },
  {
    plantId: 'plant-013',
    orgName: 'org-013',
    reportName: 'Emissions Summary',
    version: 'v2.0',
    plantName: 'Thermal Plant C',
    organisationName: 'CarbonX Inc.',
  },
  {
    plantId: 'plant-014',
    orgName: 'org-014',
    reportName: 'Emissions Summary',
    version: 'v2.0',
    plantName: 'Thermal Plant C',
    organisationName: 'CarbonX Inc.',
  },
  {
    plantId: 'plant-015',
    orgName: 'org-015',
    reportName: 'Emissions Summary',
    version: 'v2.0',
    plantName: 'Thermal Plant C',
    organisationName: 'CarbonX Inc.',
  },
  {
    plantId: 'plant-016',
    orgName: 'org-016',
    reportName: 'Emissions Summary',
    version: 'v2.0',
    plantName: 'Thermal Plant C',
    organisationName: 'CarbonX Inc.',
  },
  {
    plantId: 'plant-017',
    orgName: 'org-017',
    reportName: 'Emissions Summary',
    version: 'v2.0',
    plantName: 'Thermal Plant C',
    organisationName: 'CarbonX Inc.',
  },
];
