export const apiRoutes = {
  authentication: {
    root: '/authentication',
    login: '/login',
    signup: '/signup',
    restpassword: '/reset-password',
    forgotPassword: '/forgot-password',
    validateEmailAddress: '/validate-email-address',
    enquiry: '/enquiry',
    test: '/test',
  },
  userLogos: {
    // add tenantId and plantId further in the request
    root: 'user-logos',
    uploadLogo: '/upload-user-logo',
    getLogo: '/get-user-logo',
    deleteLogo: '/get-user-logo',
    uploadPocProfilePic: '/upload-poc-profilePic',
    getPocProfilePic: '/get-poc-profilePic',
    uploadPlantLogo: '/upload-plant-logo',
    getPlantLogo: '/get-plant-logo',
    uploadPlantPointOfContactLogo: '/upload-plant-point-of-contact-logo',
    getPlantPointOfContactLogo: '/get-plant-point-of-contact-logo',
  },
  onboardingStatus: {
    root: 'onboarding-status',
    getOnboardingStatus: '/:tenantId/onboarding-status',
  },
  onboarding: {
    root: '/onboarding',
    addOrganizationsInformation: '/add-organization-information',
    getOrganizationsInformation: '/get-organization-information',
    addPointOfContact: '/add-point-of-contact',
    getPointOfContact: '/get-point-of-contact',
  },
  plantInfo: {
    root: 'plantInfo',
    addPlantInfo: '/add-plant-info',
    updatePlantInfo: '/edit-plant-info',
    getAllPlantsInfo: '/get-all-plant-info',
    getPlantInfo: '/:tenantId/:plantId/get-plant-info',
  },

  plantAssessment: {
    root: 'plant-assessment',
    getAssessmentStatus: 'get-assessment-status',
    getCostCategories: 'get-cost-categories',
    addCostCategories: 'add-cost-categories',
    editCostCategories: 'edit-cost-categories',
    getKpiDefinition: 'get-kpi-definition',
    selectKpiDefinition: 'select-kpi-definition',
    editKpiDefinition: 'edit-kpi-definition',
    getIndustrySelectionList: 'get-industry-selection-list',
    selectIndustrySelectionList: 'select-industry-selection-list',
    editIndustrySelectionList: 'edit-industry-selection-list',
    getQuestionnairesList: 'get-questionnaires-list',
    selectQuestionnairesAnswer: 'select-questionnaires-answer',
    editQuestionnairesAnswer: 'edit-questionnaires-answer',
    startAssessmentRuleEngine: 'start-assessment-rule-engine',
    getPlanningHorizon: 'get-planning-horizon',
    selectPlanningHorizon: 'select-planning-horizon',
    changeAssessmentStatus: 'change-assessment-status',
  },
  assessorOnboarding: {
    root: 'assessor-onboarding',
    addAccessorInformation: '/add-assessor-information/:tenantId',
    filestoCSV: '/upload-metadata-files/:tenantId',
    getAssessorInformation: '/get-assessor-information/:tenantId',
    getMetadataInformation: '/get-metadata-information',
    updateAssessorInformation: '/update-assessor-information/:tenantId',
  },
  assessorFlow: {
    root: 'assessor-flow',
    getAssignedPlants: '/get-assigned-plants',
    getAllAssignedPlants: '/get-all-assigned-plants',
    getAssignedPlantinfo: '/assigned-plants-info',
    getAllMetaData: '/get-all-metadata/:tenantId',
    assignMetadata: '/assign-metadata',
    getImpactValues: '/get-impact-values',
    selectImpactValues: '/select-impact-values',
    getSelectedImpactValues: '/get-selected-impact-values',
    getSolutionsByImpactValuesSelected: '/get-solutions-by-impact-values-selected',
    selectSolutionsByImpactValuesSelected: '/select-solutions-by-impact-values-selected',
    addAboutTheCompany: '/add-about-the-company',
    summaryOfObservationsAndRecommendations: '/summary-of-observations-and-recommendations',
    addIntroduction: '/add-introduction',
    addComment: '/add-comment',
    addRoi: '/add-roi',
  },
  assessorEvaluation: {
    root: 'assessor-evaluation',
    getAllMetadata: '',
    assignMetadataToPlant: '',
  },
  metadataFileTemplate: {
    root: 'metadata-files-template',
    getMetadataFile: '/download',
  },
};
