import GlobalReduxProvider from '@/providers/GlobalReduxProvider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ThemeProvider from './ThemeProvider';

import I18nProvider from '@/providers/I18nProvider';
import LanguageInitializer from '@/components/LanguageInitializer';
import Toaster from '@/components/toaster/Toaster';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <I18nProvider>
          <ThemeProvider>
            <GlobalReduxProvider>
              <Toaster/>
              <LanguageInitializer />
              {children}
            </GlobalReduxProvider>
          </ThemeProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
