export const apiControllerPath = {
  main: {
    baseUrl: 'http://localhost:3001/api/v1',
  },
  authentication: {
    root: '/authentication',
    login: '/login',
    signup: '/signup',
    restpassword: '/reset-password',
    forgotPassword: '/forgot-password',
    validateEmailAddress: '/validate-email-address',
    test: '/test',
  },
  onboarding: {
    root: '/onboarding',
    addOrganizationsInformation: '/add-organization-information',
    getOrganizationsInformation: '/get-organization-information',
    addPointOfContact: '/add-point-of-contact',
    getPointOfContact: '/get-point-of-contact',
  },
  userLogos: {
    // add tenantId and plantId further in the request
    root: 'user-logos',
    uploadLogo: '/upload-user-logo',
    getLogo: '/get-user-logo',
    deleteLogo: '/get-user-logo',
    uploadPocProfilePic: '/upload-poc-profilePic',
    getPocProfilePic: '/get-poc-profilePic',
    uploadPlantLogo: '/upload-plant-logo',
    getPlantLogo: '/get-plant-logo',
    uploadPlantPointOfContactLogo: '/upload-plant-point-of-contact-logo',
    getPlantPointOfContactLogo: '/get-plant-point-of-contact-logo',
  },
  onboardingStatus: {
    root: 'onboarding-status',
    getOnboardingStatus: '/onboarding-status',
  },
  plantInfo: {
    root: 'plantInfo',
    addPlantInfo: '/add-plant-info',
    updatePlantInfo: '/edit-plant-info',
    getAllPlantsInfo: '/get-all-plant-info',
    getPlantInfoById: '/get-plant-info',
  },
  assessorOnboarding: {
    root: '/assessor-onboarding',
    addAssessorInformation: '/add-assessor-information/',
    getAssessorInformation: '/get-assessor-information/',
    addPointOfContact: '/:tenantId/add-point-of-contact',
    getPointOfContact: '/:tenantId/get-point-of-contact',
    // filestoCSV: '/upload-metadata-files/',
    getMetadataInformation: '/get-metadata-information',
    updateAssessorInformation: '/update-assessor-information/',
    uploadQuestionnaires: '/upload-questionnaries/',
    uploadCostProfile: '/upload-cost-profile/',
    uploadIndustrySelection: '/upload-industry-selection/',
    uploadKPI: '/upload-kpi/',
    uploadPlanningHorizon: '/upload-planning-horizon/',
    uploadCostProfileLookup: '/upload-costprofile-lookup/',
    uploadIndustrySelectionLookup: '/upload-industry-selection-lookup/',
    uploadKPILookup: '/upload-kpi-lookup/',
    uploadIndustryAssessmentMatrix: '/upload-industry-assessment-matrix/',
    uploadSolutionMetadata: '/upload-solution-metadata/',
    uploadBandDefinition: '/upload-band-definition/',

    viewMetadataFile: '/view-metadata-file',
  },
  assessorFlow: {
    root: 'assessor-flow',
    getAssignedPlants: '/get-assigned-plants/:tenantId',
    getAllAssignedPlants: '/get-all-assigned-plants',
    getAssignedPlantinfo: '/assigned-plants-info',
    getAllMetaData: '/get-all-metadata',
    assignMetadata: '/assign-metadata',
    getImpactValues: '/get-impact-values',
    getSelectedImpactValues: '/get-selected-impact-values',
    selectImpactValues: '/select-impact-values',
    getSolutionsByImpactValuesSelected: '/get-solutions-by-impact-values-selected',
    selectSolutionsByImpactValuesSelected: '/select-solutions-by-impact-values-selected',
    addAboutTheCompany: '/add-about-the-company',
    summaryOfObservationsAndRecommendations: '/summary-of-observations-and-recommendations',
    addIntroduction: '/add-introduction',
    addComment: '/add-comment',
    addRoi: '/add-roi',
    getReportData: '/get-report-data',
  },
  plantAssessment: {
    root: '/plant-assessment',
    getAssessmentStatus: '/get-assessment-status',
    getCostCategories: '/get-cost-categories',
    addCostCategories: '/add-cost-categories',
    editCostCategories: '/edit-cost-categories',
    getKpiDefinition: '/get-kpi-definition',
    selectKpiDefinition: '/select-kpi-definition',
    editKpiDefinition: '/edit-kpi-definition',
    getIndustrySelectionList: '/get-industry-selection-list',
    selectIndustrySelectionList: '/select-industry-selection-list',
    editIndustrySelectionList: '/edit-industry-selection-list',
    getQuestionnairesList: '/get-Questionnaires-list',
    selectQuestionnairesAnswer: '/select-Questionnaires-answer',
    editQuestionnairesAnswer: '/edit-Questionnaires-answer',
    startAssessmentRuleEngine: '/start-assessment-rule-engine',
    getPlanningHorizon: '/get-planning-horizon',
    selectPlanningHorizon: '/select-planning-horizon',
    changeAssessmentStatus: '/change-assessment-status',
    changeQuestionsStatus: '/change-question-status',
  },
  metadataFileTemplate: {
    root: 'metadata-files-template',
    getMetadataFile: '/download',
  },
  enquiry: {
    root: '/enquiries',
  },

  report: {
    root: 'report',
    createReport: '/create-report/',
    previewReport: '/preview-report',
    downloadreport: '/download-report',
    emailNotificationForReport: '/email-notification-after-save-report',
  },
};
