export const apiControllerPath = {
  main: {
    app: '/api',
  },
  authentication: {
    root: 'authentication',
    login: '/login',
    signup: '/signup',
    restpassword: '/reset-password',
    forgotPassword: '/forgot-password',
    validateEmailAddress: '/validate-email-address',
    enquiry: '/enquiry',
    test: '/test',
  },
  onboardingStatus: {
    root: 'onboarding-status',
    getOnboardingStatus: '/:tenantId/onboarding-status',
  },
  onboarding: {
    root: '/onboarding',
    addOrganizationsInformation: '/add-organization-information',
    getOrganizationsInformation: '/:tenantId/get-organization-information',
    addPointOfContact: '/:tenantId/add-point-of-contact',
    getPointOfContact: '/:tenantId/get-point-of-contact',
  },
  plantInfo: {
    root: 'plantInfo',
    addPlantInfo: '/:tenantId/add-plant-info',
    updatePlantInfo: '/:tenantId/:plantId/edit-plant-info',
    getAllPlantsInfo: '/:tenantId/get-all-plant-info',
    getPlantInfo: '/:tenantId/:plantId/get-plant-info',
  },

  plantAssessment: {
    root: 'plant-assessment',
    getAssessmentStatus: 'get-assessment-status',
    getCostCategories: 'get-cost-categories',
    addCostCategories: 'add-cost-categories',
    editCostCategories: 'edit-cost-categories',
    getKpiDefinition: 'get-kpi-definition',
    selectKpiDefinition: 'select-kpi-definition',
    editKpiDefinition: 'edit-kpi-definition',
    getIndustrySelectionList: 'get-industry-selection-list',
    selectIndustrySelectionList: 'select-industry-selection-list',
    editIndustrySelectionList: 'edit-industry-selection-list',
    getQuestionnairesList: 'get-questionnaires-list',
    selectQuestionnairesAnswer: 'select-questionnaires-answer',
    editQuestionnairesAnswer: 'edit-questionnaires-answer',
    startAssessmentRuleEngine: 'start-assessment-rule-engine',
    getPlanningHorizon: 'get-planning-horizon',
    selectPlanningHorizon: 'select-planning-horizon',
    changeAssessmentStatus: 'change-assessment-status',
  },
  assessorOnboarding: {
    root: 'assessor-onboarding',
    addAccessorInformation: '/add-assessor-information/:tenantId',
    filestoCSV: '/upload-metadata-files/:tenantId',
    getAssessorInformation: '/get-assessor-information/:tenantId',
    getMetadataInformation: '/get-metadata-information',
    updateAssessorInformation: '/update-assessor-information/:tenantId',
  },
  assessorFlow: {
    root: 'assessor-flow',
    getAssignedPlants: '/get-assigned-plants/:tenantId',
    getAllAssignedPlants: '/get-all-assigned-plants/:assessorId',
    getAssignedPlantinfo: '/assigned-plants-info/:tenantId/:plantId',
    getAllMetaData: '/get-all-metadata/:tenantId',
    assignMetadata: '/assign-metadata',
    getImpactValues: '/get-impact-values',
    selectImpactValues: '/select-impact-values',
    getSelectedImpactValues: '/get-selected-impact-values',
    getSolutionsByImpactValuesSelected: '/get-solutions-by-impact-values-selected',
    selectSolutionsByImpactValuesSelected: '/select-solutions-by-impact-values-selected',
  },
  assessorEvaluation: {
    root: 'assessor-evaluation',
    getAllMetadata: '',
    assignMetadataToPlant: '',
  },
  metadataFileTemplate: {
    root: 'metadata-files-template',
    getMetadataFile: '/download',
  },
};
